### ISSUE TITLE
semanticuiform not semanticuiforms

### ISSUE THREAD

**Issue by ahmedelsers** [thetarkus/django-semantic-ui-forms#1]
Hello

Add semanticuiform to your INSTALLED_APPS.  not semanticuiforms, without the s at the end.

**Comment by thetarkus** [comment]
The app's name is `semanticuiforms`, with the `s`. Without the `s` the app will not be able to be found and therefore cannot be imported.

Perhaps you're confusing this project's app with another?

**Comment by thisfieldmustbefilled** [comment]
Do you have any plans to extend this app to provide Semantic UI blocks and elements support, not forms only?

**Comment by thetarkus** [comment]
@thisfieldmustbefilled Not in this repository, but I'm not against the idea. What types of elements do you think would benefit as template tags or what Django systems (like forms) could be made wrappable with semantic ui?

**Comment by thisfieldmustbefilled** [comment]
@thetarkus ha-ha, I'm very ambitious when talking about other's job. I think all the layouts, elements, collections, views and modules provided on official website could be implemented as macros. I found this repo (https://github.com/gpichot/django-semantic-ui), but it seems to be not quite understandable and possibly outdated.

**Comment by thetarkus** [comment]
@thisfieldmustbefilled If I get some free time this is something I definitely could use. Would be tough considering how many options you can cram into a Semantic UI element. Perhaps I'll get to it sometime or contribute to a semi-active one (if it is created ;-)).
